export enum ASYNC_STORAGE_ENUM {
  USER_EMAIL = 'user_email',
  ID_TOKEN = 'ID_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  NOTI_TOKEN = 'NOTI_TOKEN',
  TOKEN_TIME = 'TOKEN_TIME',
  USER_ID = 'USER_ID',
  IS_LOGGED_IN = 'IS_LOGGED_IN',
  IS_ONBOARDING_DONE = 'IS_ONBOARDING_DONE',
  NOTIFICATION_RADIUS = 'notification_radius',
  NOTIFICATION_INTERVAL = 'notification_interval',
  LAST_CHECK_FROM_CLIENT = 'last_check_from_client',
}
